import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Query_Client from "../components/query-Client";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = {
  title: "E-MITRA SEVA KENDRA",
  description: "Generated by Datastone Solutions",
  manifest:"/manifest.json"
  };


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Query_Client>{children}</Query_Client></body>
    </html>
  )
}
